### ISSUE TITLE
Armory stuck on "Initializing Bitcoin Engine" after changing the database location

### ISSUE THREAD

**Issue by fresheneesz** [etotheipi/BitcoinArmory#298]
All three bars are empty, and the little wheel just keeps spinning. I'm seeing this problem after following these instructions on windows: https://support.bitcoinarmory.com/kb/article/16-change-or-move-the-blockchain-database-storage-location-for-armory-and-bitcoin-core

I already have a --satoshi-datadir flag in my shortcut that I added as per the instructions in that link. What could be going wrong here?

**Comment by fresheneesz** [comment]
Potentially related issues: 
https://github.com/etotheipi/BitcoinArmory/issues/181
https://github.com/etotheipi/BitcoinArmory/issues/268

**Comment by fresheneesz** [comment]
I noticed that when I try to start up Bitcoin core, it asks me where I want to put the database, and I specify the place I moved the database to. It then tells me there's an "error opening block database" and asks me if i want to rebuild the block database now. I can abort, or press ok. If i press ok it says "error opening block database". Dick..

**Comment by fresheneesz** [comment]
I tried reinstalling bitcoin core, but i get the same problem - it seems to not like the harddrive i'm trying to put it on.

**Comment by fresheneesz** [comment]
This is probably related: https://github.com/bitcoin/bitcoin/issues/6200

**Comment by fresheneesz** [comment]
Ok, the solution was to run a chkdisk on the drive i was using to store these files. I was only able to figure this out by looking in Bitcoin Core's debug.log file. Can we please keep this issue open until Armory displays the proper error message to the user telling them what needs to be done (chkdsk)?

**Comment by droark** [comment]
Hello. I'm going to close this issue. As mentioned in the referenced issue, all bets are off if a disk is improperly unmounted. Expecting engineers to write code anticipating such a case is, in general, a very bad idea. All bets really are off, and there are any number of problems that could show up in any number of permutations. How are engineers supposed to know what exactly one should do? The far simpler solution is to just not engage in dangerous behavior. I've been properly unloading my external drives since 2002 or so and have never had problems like these.

In addition, I've written forward-facing software. Trust me, it's easy for well-meaning messages to confuse users. Telling people to do things like run *chkdsk* will just cause users to expect us to fix their problems, even if it's really not an Armory issue.

If the BC Core contributors somehow decide to add logic looking for such a case, perhaps we'll consider adding it. For now, we're going to proceed with what we have. Sorry.

**Comment by fresheneesz** [comment]
@droark A well meaning and misleading message is more helpful than no message at all. Should be easy to pass that message through. Imagining that this is an edgecase with most users is a mistake if you want this software to become more mainstream.

**Comment by fresheneesz** [comment]
Here's some evidence that no one freaking safely removes drives: 

https://www.google.com/search?q=life%27s+too+short+to+remove+usb+safely&num=20&safe=off&tbm=isch&imgil=5XAmcgluP3r0FM%253A%253BcwqFgAQyrfBeSM%253Bhttp%25253A%25252F%25252Fwww.someecards.com%25252Fusercards%25252Fviewcard%25252FMjAxMS02YmE3MDk0NzE4ZGUyMDlh&source=iu&pf=m&fir=5XAmcgluP3r0FM%253A%252CcwqFgAQyrfBeSM%252C_&biw=1080&bih=1795&usg=__LrRcGjvSM3tYRh68bxbAY6V8I6M%3D&ved=0CC0Qyjc&ei=_N6SVaMwg9WgBKe6nqgL#imgrc=5XAmcgluP3r0FM%3A&usg=__LrRcGjvSM3tYRh68bxbAY6V8I6M%3D
