### ISSUE TITLE
Make Armory work with an external node that provides a tx index

### ISSUE THREAD

**Issue by stevenroose** [etotheipi/BitcoinArmory#309]
I'm running a btcd node (the Go implementation) on a server at home. 

It would be nice if Armory could connect to that node instead of requiring a node on the actual machine as well.
The node has a full tx index by address, so Armory should be able to get all the information it needs from it...

**Comment by spaz926** [comment]
Is the computer running Armory and the server running the node on the same network?

**Comment by stevenroose** [comment]
I think so. The node is also externally accessible, but when I'm home its on the same network, yes.

But it's not bitcoind, it's btcd..

**Comment by droark** [comment]
Hello. Unfortunately, due to technical reasons, Armory is currently designed to require an instance of Bitcoin Core (or XT, or maybe btcd, although I've never tried it) on the same computer. Believe me, we've had many requests over the last 2-3 years to change this and make it possible to connect to remote instances. For many reasons, this just hasn't happened yet. Maybe it will someday. I know Alan has no problem with the idea. It's just the usual factors at play (security, having time to actually code and thoroughly test the feature, etc.). I can't make any promises. All I can say is that it is something we know about, and it is something we want to do when the time is right.

Thanks for the report! We really appreciate it.

**Comment by stevenroose** [comment]
@droark If a running instance on the same machine is required, can I assume Armory is using more than just the API bitcoind provides? (Like the actual block files?)
Because, in that case, btcd or any alternative implementation that uses the same RPC API as bitcoind does won't work.

I used Armory several years ago and back then it had to parse all block files on startup instead of using the API of the node, is that still the case?

**Comment by droark** [comment]
Yes, Armory still reads the blockchain files.
