### ISSUE TITLE
Armory Crashes when connecting to Bitcoin Core with pruning

### ISSUE THREAD

**Issue by spaz926** [etotheipi/BitcoinArmory#311]
I have Bitcoin Core set to prune to 550MB. Armory crashes when trying to connect to it.

If I open Armory in offline mode it will open fine.

Armory version: 0.93.2
Bitcoin Core version: 0.11.0

Is it possible to add support for pruned blocks?

**Comment by droark** [comment]
Hello. I just spoke to a dev who knows more about pruning. Here's what I was told.

"pruning will crash 0.93. 0.94 can handle it just fine but you wont see spend history. it's only really useful to see your balance. pruned blocks only maintain UTXOs so that comes with the territory."

We also have other ideas related to expanding Armory capabilities. Pruning support will be included, so pruning shouldn't be a problem moving forward.

Thanks for the report!
