### ISSUE TITLE
SwigClient.cpp:61 - unexpected return value

### ISSUE THREAD

**Issue by fresheneesz** [etotheipi/BitcoinArmory#339]
So I'm opening Armory after downloading the entire blockchain via bitcoin core, and it just sits there in offline mode saying its "preparing database". I exported the log file and see a few conspicuous errors at the bottom of it. They all look something like this:

`ERROR - 1495752189: (..\SwigClient.cpp:61) unexpected return value`

So what's going on here? And why does Armory *still* not correctly handle errors like this and report them to the user via the GUI?

**Comment by droark** [comment]
#341.

**Comment by fresheneesz** [comment]
@droark Why are you reminding me of my own ticket?

**Comment by droark** [comment]
Hi. I just went down the line and posted the link for any issue/PR posted in the past 8-9 months. I also hope it would inspire some people to close the tickets too, so that the message about this repo being dead would stay up near the top. :) A *lot* of people have been getting back into Armory over the past few months. I'm trying to minimize confusion whenever I can. (Yeah, I wish this repo could be closed or whatever. It would've happened by now if it was in the cards.)

**Comment by fresheneesz** [comment]
@droark Ah gotcha, done
